import = [
  "~/.config/alacritty/alacritty-theme/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

startup_mode = "Maximized"

decorations = "Buttonless"
opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"

size = 16

[selection]
save_to_clipboard = true
